name: DataPipeline

on: [push]

jobs: 
  data-pipeline: 
    name: Data Pipeline
    runs-on: ubuntu-latest 
    env:
      SEASON_YEAR: 2015
    steps:
    # check-out the repository so job can access all your code
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9.7
      # install poetry 
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    # if an environment already exists, load it; otherwise create a new one 
    - name: Load Cached Virtual Environment
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
  # if no cache exists, install packages 
      run: poetry install --no-interaction --no-root
    - name: NFL data refresh
      run: |
        source .venv/bin/activate
        mkdir staging_datasets
        echo "contents of root dir"
        ls
        echo "root directory"
        pwd
    #     python pipeline/collect/collect_calendar.py --season_year $SEASON_YEAR
    #     python pipeline/process/process_calendar.py --season_year $SEASON_YEAR      
    #     python pipeline/collect/collect_players.py --season_year $SEASON_YEAR
    #     python pipeline/process/process_players.py --season_year $SEASON_YEAR
    #     python pipeline/collect/collect_stats.py --season_year $SEASON_YEAR
    #     python pipeline/process/process_stats.py --season_year $SEASON_YEAR
    #     python pipeline/collect/collect_weather.py --season_year $SEASON_YEAR
    #     python pipeline/process/process_weather.py --season_year $SEASON_YEAR      
    #     python pipeline/process/process_defense.py --season_year $SEASON_YEAR   
    #     python pipeline/load/load_data.py --season_year $SEASON_YEAR
    # - name: Commit new data to datasets directory
    #   shell: bash
    #   run: |
    #     echo "Loading data to git"
    #     if [[ "$(git status --porcelain)" != "" ]]; then
    #         git config --global user.name 'MarkLeBoeuf'
    #         git config --global user.email 'markleboeuf2015@u.northwestern.edu'
    #         git add src/fantasyfootball/datasets/*.gz        
    #         git commit -m "data: auto update historical NFL data"
    #         git push
    #     fi


